# Generated by Django 5.1.7 on 2025-03-31 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(verbose_name='Фамилия')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.TextField(verbose_name='Место выступления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('completed', models.BooleanField(verbose_name='Статус выполнения')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('cnt_artists', models.IntegerField(verbose_name='Количество артистов')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='ShowRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ставка')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_type', models.TextField(verbose_name='Тип шоу')),
            ],
            options={
                'verbose_name': 'Тип шоу',
                'verbose_name_plural': 'Типы шоу',
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата')),
                ('paid', models.BooleanField(verbose_name='Статус выплаты')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.artist')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.order')),
            ],
            options={
                'verbose_name': 'Заказ и артист',
                'verbose_name_plural': 'Заказы и артисты',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='orders',
            field=models.ManyToManyField(through='lumos.Earning', to='lumos.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.performance'),
        ),
        migrations.CreateModel(
            name='ArtistPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.artist')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.performance')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.showrate')),
            ],
            options={
                'verbose_name': 'Номер и артист',
                'verbose_name_plural': 'Номера и артисты',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='performances',
            field=models.ManyToManyField(through='lumos.ArtistPerformance', to='lumos.performance'),
        ),
        migrations.AddField(
            model_name='showrate',
            name='show_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.type'),
        ),
        migrations.AddField(
            model_name='performance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumos.type'),
        ),
    ]
